name: Build Kernel for Tiffany

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile Kernel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk \
        gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
        default-jdk git gnupg flex bison gperf build-essential zip curl libc6-dev libncurses-dev \
        libx11-dev libreadline-dev libgl1 libgl1-mesa-dev python3 make sudo gcc g++ bc grep \
        tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev \
        libtinfo6 make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools \
        zstd binutils --fix-missing

        wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
        sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb
        
    - name: Download Linaro GCC 7.5 Toolchain
      run: |
        wget https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/linaro-aarch64-7.5.tar.xz
        tar -xf linaro-aarch64-7.5.tar.xz
        echo "$GITHUB_WORKSPACE/linaro-aarch64-7.5/bin" >> $GITHUB_PATH

    - name: Make Output Directory
      run: mkdir out

    - name: Configure Kernel
      run: |
        make O=out ARCH=arm64 tiffany_defconfig \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Build Kernel
      run: |
        make -j$(nproc) O=out ARCH=arm64 \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zImage-dtb
        path: out/arch/arm64/boot/Image.gz-dtb
